USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS HEALTHCARE_GENOMICS;

USE DATABASE HEALTHCARE_GENOMICS;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CURATED;
CREATE SCHEMA IF NOT EXISTS AI;
CREATE SCHEMA IF NOT EXISTS ML;
CREATE SCHEMA IF NOT EXISTS SEARCH;
CREATE SCHEMA IF NOT EXISTS LAKE;
CREATE SCHEMA IF NOT EXISTS APP;
