USE ROLE SYSADMIN;
USE DATABASE HEALTHCARE_GENOMICS;
USE SCHEMA RAW;

CREATE OR REPLACE STAGE HEALTHCARE_GENOMICS.RAW.GENOMICS_S3_STAGE
  URL = 's3://sg-healthcare-demos-2026/genomics/'
  STORAGE_INTEGRATION = HEALTHCARE_DEMOS_S3_INTEGRATION
  FILE_FORMAT = (TYPE = PARQUET);

-- Glue Catalog Integration (for Iceberg export when AWS is active)
-- CREATE OR REPLACE CATALOG INTEGRATION GENOMICS_GLUE_CATALOG
--   CATALOG_SOURCE = GLUE
--   CATALOG_NAMESPACE = 'healthcare_genomics_iceberg'
--   TABLE_FORMAT = ICEBERG
--   GLUE_AWS_ROLE_ARN = 'arn:aws:iam::__AWS_ACCOUNT_ID__:role/snowflake-healthcare-s3-role'
--   GLUE_CATALOG_ID = '__AWS_ACCOUNT_ID__'
--   GLUE_REGION = 'us-west-2'
--   ENABLED = TRUE;
