USE ROLE SYSADMIN;
USE DATABASE HEALTHCARE_GENOMICS;
USE SCHEMA CURATED;

--------------------------------------------------------------------
-- VARIANT_SUMMARY: Gene x Cohort x Clinical Significance aggregation
--------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE VARIANT_SUMMARY
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    v.GENE,
    v.COHORT,
    v.CLINICAL_SIGNIFICANCE,
    COUNT(*) AS VARIANT_COUNT,
    COUNT(DISTINCT v.PATIENT_ID) AS PATIENT_COUNT,
    AVG(v.ALLELE_FREQUENCY) AS AVG_ALLELE_FREQUENCY,
    MIN(v.ALLELE_FREQUENCY) AS MIN_ALLELE_FREQUENCY,
    MAX(v.ALLELE_FREQUENCY) AS MAX_ALLELE_FREQUENCY,
    RATIO_TO_REPORT(COUNT(*)) OVER (PARTITION BY v.GENE) AS COHORT_FRACTION
FROM RAW.VARIANTS v
GROUP BY v.GENE, v.COHORT, v.CLINICAL_SIGNIFICANCE;

--------------------------------------------------------------------
-- COHORT_DEMOGRAPHICS: Per-cohort demographic statistics
--------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE COHORT_DEMOGRAPHICS
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    p.COHORT,
    COUNT(*) AS TOTAL_PATIENTS,
    AVG(p.AGE) AS AVG_AGE,
    MEDIAN(p.AGE) AS MEDIAN_AGE,
    SUM(CASE WHEN p.SEX = 'M' THEN 1 ELSE 0 END) AS MALE_COUNT,
    SUM(CASE WHEN p.SEX = 'F' THEN 1 ELSE 0 END) AS FEMALE_COUNT,
    MODE(p.ETHNICITY) AS MOST_COMMON_ETHNICITY,
    MODE(p.DIAGNOSIS) AS MOST_COMMON_DIAGNOSIS,
    SUM(CASE WHEN p.STATUS = 'Active' THEN 1 ELSE 0 END) AS ACTIVE_COUNT,
    SUM(CASE WHEN p.STATUS = 'Withdrawn' THEN 1 ELSE 0 END) AS WITHDRAWN_COUNT
FROM RAW.PATIENTS p
GROUP BY p.COHORT;

--------------------------------------------------------------------
-- BIOBANK_INVENTORY: Specimen type x Status aggregation
--------------------------------------------------------------------
CREATE OR REPLACE DYNAMIC TABLE BIOBANK_INVENTORY
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT
    b.SPECIMEN_TYPE,
    b.STATUS,
    COUNT(*) AS SPECIMEN_COUNT,
    SUM(b.QUANTITY_ML) AS TOTAL_VOLUME_ML,
    AVG(b.QUALITY_SCORE) AS AVG_QUALITY_SCORE,
    MIN(b.COLLECTION_DATE) AS EARLIEST_COLLECTION,
    MAX(b.COLLECTION_DATE) AS LATEST_COLLECTION,
    COUNT(DISTINCT b.PATIENT_ID) AS UNIQUE_PATIENTS
FROM RAW.BIOSPECIMENS b
GROUP BY b.SPECIMEN_TYPE, b.STATUS;
