USE ROLE SYSADMIN;
USE DATABASE HEALTHCARE_GENOMICS;
USE SCHEMA SEARCH;

CREATE OR REPLACE CORTEX SEARCH SERVICE PUBLICATION_SEARCH
    ON RAW.PUBLICATIONS
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
    SEARCH_COLUMN = 'ABSTRACT'
    ATTRIBUTES = 'TITLE', 'JOURNAL', 'GENES_MENTIONED'
    AS (
        SELECT
            PUBLICATION_ID,
            TITLE,
            ABSTRACT,
            JOURNAL,
            GENES_MENTIONED,
            AUTHORS,
            DOI,
            PUBLISH_DATE
        FROM RAW.PUBLICATIONS
    );
