USE ROLE SYSADMIN;
USE DATABASE HEALTHCARE_GENOMICS;
USE SCHEMA ML;

CREATE OR REPLACE VIEW VARIANT_FREQUENCY_SERIES AS
SELECT
    GENE AS SERIES_KEY,
    DETECTED_DATE AS TIMESTAMP,
    AVG(ALLELE_FREQUENCY) AS VALUE
FROM RAW.VARIANTS
GROUP BY GENE, DETECTED_DATE
ORDER BY GENE, DETECTED_DATE;

CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION VARIANT_ANOMALY_MODEL(
    INPUT_DATA => SYSTEM$REFERENCE('VIEW', 'VARIANT_FREQUENCY_SERIES'),
    SERIES_COLNAME => 'SERIES_KEY',
    TIMESTAMP_COLNAME => 'TIMESTAMP',
    TARGET_COLNAME => 'VALUE'
);
