USE ROLE SYSADMIN;
USE DATABASE HEALTHCARE_GENOMICS;
USE SCHEMA LAKE;

-- In AWS mode with active Glue integration, this would be:
-- CREATE OR REPLACE ICEBERG TABLE COHORT_EXPORT
--     CATALOG = 'GENOMICS_GLUE_CATALOG'
--     EXTERNAL_VOLUME = 'HEALTHCARE_EXT_VOL'
--     BASE_LOCATION = 'cohort_export/'
-- AS ...

CREATE OR REPLACE TABLE COHORT_EXPORT AS
SELECT DISTINCT
    p.PATIENT_ID,
    p.COHORT,
    p.AGE,
    p.SEX,
    p.ETHNICITY,
    p.DIAGNOSIS,
    brca.CLINICAL_SIGNIFICANCE AS BRCA1_SIGNIFICANCE,
    brca.ALLELE_FREQUENCY AS BRCA1_AF,
    tp53.CLINICAL_SIGNIFICANCE AS TP53_SIGNIFICANCE,
    tp53.ALLELE_FREQUENCY AS TP53_AF,
    CURRENT_TIMESTAMP() AS EXPORT_TIMESTAMP
FROM RAW.PATIENTS p
JOIN RAW.VARIANTS brca
    ON p.PATIENT_ID = brca.PATIENT_ID
    AND brca.GENE = 'BRCA1'
    AND brca.CLINICAL_SIGNIFICANCE = 'Pathogenic'
JOIN RAW.VARIANTS tp53
    ON p.PATIENT_ID = tp53.PATIENT_ID
    AND tp53.GENE = 'TP53'
    AND tp53.CLINICAL_SIGNIFICANCE IN ('Pathogenic', 'Likely Pathogenic')
LIMIT 200;
